import pandas as pd
import argparse
import tskit

parser = argparse.ArgumentParser()
parser.add_argument("-input_csv", help="Path and filename of cp copyprobsperlocus.out.csv file", required=True)
parser.add_argument("-input_ts", help="Path and filename of ts generated by msprime", required=True)
parser.add_argument("-out", help="Path to save cp best guess csv to", required=True)
args = parser.parse_args()

df = pd.read_csv(args.input_csv, delim_whitespace=True)
ts = tskit.load(args.input_ts)


rowstoignore = list(df[df['pos'].str.contains("HAP")==True].index)
introws = list()
for i in list(df.index):
    if i not in rowstoignore:
        introws.append(i)

list_of_variants = list()
for variant in ts.variants():
    list_of_variants.append(variant.site.position)

labellist = list()
for i in range(2 * (len(df.columns) - 1)):
    for j in range(len(list_of_variants)+1):
        labellist.append("HAP_" + str(i))

df['recipient_hap_id'] = labellist
df_reduced = df.iloc[introws]

column_selection = df_reduced.shape[1] - 1
df_reduced['donor_ind'] = df_reduced.iloc[:, 1:column_selection].astype(float).idxmax(axis=1)

df_final_ancestry = df_reduced[['recipient_hap_id', 'pos', 'donor_ind']]
df_final_ancestry.to_csv(args.out + '/df_fs_final_ancestry.csv')
