phasefiles:combined_panel/combined_phasefile
recombfiles:combined_panel/combined_recombfile
popidfile:combined_panel/combined_pop_ids
donoridfile:will_modernvsancient.donors
refdonorfile:
popNeinf:57.5958
popmuinf:0.00116721
